// This file can be replaced during build by using the `fileReplacements` array.
// `ng build ---prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment: any = {
  production: false,
  version: env.npm_package_version + '-dev',
  serverUrl: {
    // Server - IIST
    oauth: 'http://123.24.205.97:8880/api-gateway/oauth-service',
    file: 'http://123.24.205.97:8880/api-gateway/file-storage',
    // political: 'http://123.24.205.97:8880/api-gateway/political-system',

    // Server - Viettel
    // oauth: 'http://10.58.71.134:8880/api-gateway/oauth-service',
    // file  : 'http://10.58.71.134:8880/api-gateway/file-storage',
    // political: 'http://10.58.71.134:8880/api-gateway/political-system',
    // nimsTransService: 'http://192.168.100.108:8084/nims-transmission-service/', // Server Test
    // political: 'http://192.168.1.62:8084/', // Toan
    // political: 'http://192.168.1.82:8084/', // Van
    // political: 'http://localhost:8084/',
    // nimsGeoService: 'http://192.168.1.65:8060/nims-geo-service/',
    nimsGeoService: 'http://192.168.100.108:8060/nims-geo-service/',
    nimsTransService: 'http://localhost:8084/nims-transmission-service/'
  },
  dateFormatCalendar: 'dd/mm/yy',
  dateFormat: 'dd/MM/yyyy',
  dateFormat_vn: 'dd/MM/yyyy HH:mm:ss',
  rowsPerPageOptions: [5, 10, 20],
  pageDefault: 1,
  first: 0,
  rowsDefault: 10,
  rowsModal: 5,
  sortOrderDefault: 1,
  typeFile: {
    fileAttachment: 1,
    appendixFileForm: 2,
    attachedDocuments: 3
  },
  file: {
    validType: `.xls,.xlsx,.doc,.docx,.txt`,
    validTypeOffice: `.xls,.xlsx,.doc,.docx,.pdf`,
    validTypeSign: `.pdf`,
    maxSize: 200,
    validTypeOfficeExcel: `.xls,.xlsx`,
    validTypeOfficeWord: `.doc,.docx`
  }
};
/** custom Constants variable */
export const Constants = {
  applicationCode: 'VHR_3',
  userToken: 'userToken',
  navState: 'navState',
  accessToken: 'access_token',
  tokenExpiresIn: 'token_expires_in'
};
export const UrlConfig: any = {
  clientAddress: 'http://localhost:4200',
  ssoAddress: 'https://125.212.225.85:8445/cas'
};
/*
 * In development mode, to ignore zone related error stack frames such as
 * `zone.run`, `zoneDelegate.invokeTask` for easier debugging, you can
 * import the following file, but please comment it out in production mode
 * because it will have performance impact when throw error
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
