// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: false,
  version: env.npm_package_version + '-dev',
  serverUrl: {
    // Server - IIST
    oauth: 'http://123.24.205.97:8880/api-gateway/oauth-service',
    file: 'http://123.24.205.97:8880/api-gateway/file-storage',
    // political: 'http://123.24.205.97:8880/api-gateway/political-system',

    // Server - Viettel
    // oauth: 'http://10.58.71.134:8880/api-gateway/oauth-service',
    // file  : 'http://10.58.71.134:8880/api-gateway/file-storage',
    // political: 'http://10.58.71.134:8880/api-gateway/political-system',
    // link test
    // political: 'http://123.24.205.97:8079/',
    // local
    political: 'http://localhost:8084/',

    nimsGeoService: 'http://localhost:8060/nims-geo-service/',
    nimsTransService: 'http://localhost:8060/nims-transmission-service/'
  },
  dateFormatCalendar: 'dd/mm/yy',
  dateFormat: 'dd/MM/yyyy',
  dateFormat_vn: 'dd/MM/yyyy HH:mm:ss',
  rowsPerPageOptions: [5, 10, 20],
  pageDefault: 1,
  first: 0,
  rowsDefault: 10,
  rowsModal: 5,
  sortOrderDefault: 1,
  typeFile: {
    fileAttachment: 1,
    appendixFileForm: 2,
    attachedDocuments: 3
  },
  file: {
    validType: `.xls,.xlsx,.doc,.docx,.txt`,
    validTypeOffice: `.xls,.xlsx,.doc,.docx,.pdf`,
    validTypeSign: `.pdf`,
    maxSize: 200,
  }
};

/** custom Constants variable */
export const Constants = {
  applicationCode: 'VHR_3',
  userToken: 'userToken',
  navState: 'navState',
  accessToken: 'access_token',
  tokenExpiresIn: 'token_expires_in'
  ,
};
