heat_template_version: queens

description: >
  HOT template to deploy two servers into an existing neutron tenant network and
  assign floating IP addresses to each server so they are routable from the
  public network.
parameters:
  server_name:
    type: string
    description: Name of servers
  key_name:
    type: string
    description: Name of keypair to assign to servers
  image:
    type: string
    description: Name of image to use for servers
  flavor:
    type: string
    description: Flavor to use for servers
  public_net_id:
    type: string
    description: >
      ID of public network for which public IP addresses will be allocated
  public_subnet_id:
    type: string
    description: >
      ID of public sub network for which public IP addresses will be allocated
  private_net_id:
    type: string
    description: ID of private network into which servers get deployed
  private_subnet_id:
    type: string
    description: ID of private sub network into which servers get deployed
  gitlab_merge_source_branch:
    type: string
    description: gitlab staging source branch
  gitlab_merge_target_branch:
    type: string
    description: gitlab staging target branch

  gitlab_project_api_url:
    type: string
    description: gitlab merge request api url

resources:
  staging_server:
    type: OS::Nova::Server
    properties:
      name: { get_param: server_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
      - port: { get_resource: staging_server_port }

  staging_server_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: public_net_id }
      security_groups: ["default"]

outputs:
  staging_server_public_ip:
    description: Public IP address of staging_server in public network
    value: { get_attr: [ staging_server, first_address ] }
