server:
  port: 8061

spring:
  cloud:
    config:
      allowOverride: true
      overrideSystemProperties: false
  devtools:
    remote:
      secret: nims

opentracing:
  jaeger:
    const-sampler:
      decision: true
