server:
  port: 8084

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  file: ./log/transmission-service.log
  file.max-history: 10
  file.max-size: 10MB
  level:
    ROOT: info

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.mysql.MySQL5InnoDBSpatialDialect
  datasource.url: jdbc:mariadb://123.24.205.97:3310/nims
  datasource.username: iist
  datasource.password: Hanoi@1900
  datasource.driver-class-name: org.mariadb.jdbc.Driver
  h2.console.enabled: true

app:
  prefix: nims-transmission-service
