---
- name: Create docker compose file for service
  template:
    src: service-docker-compose.j2
    dest: "{{working_dir}}/{{service_name}}.yml"

- name: Start service containers
  shell:
    cmd: "docker-compose -p vsmart -f {{service_name}}.yml up -d"
    chdir: "{{working_dir}}"

- name: wait for service port up
  wait_for:
    host: "127.0.0.1"
    port: "{{service_port}}"
    timeout: 360

- name: wait for service list refresh
  shell:
    cmd: "sleep {{refresh_service_list_timeout}}"
  when: service_name != "configuration-service" and service_name != "discovery-service" and service_name != "gateway-service"
