---
- name: Create inventory files for production environments
  hosts: local
  template:
    src: "deploy_vsmart_template.j2"
    dest: "{{CURRENT_JENKINS_LOCAL_DIR}}/deploy_vsmart.yml"
    mode: 0644
