---
- name: Create secret environment file for production environments
  hosts: local
  template:
    src: "secret.yml.j2"
    dest: "{{CURRENT_JENKINS_LOCAL_DIR}}/group_vars/all/secret.yml"
    mode: 0600
